### ISSUE TITLE
Vue-router error

### ISSUE THREAD

**Issue by Vertygo** [devkimchi/Vue.js-with-ASP.NET-Core-Sample#2]
Hi Justin,

I was following your blog post about writing aspnet core app with Vue and I wanted to do it using VS 2017 + latest packages available for vue2 + webpack2 and it seems that I got everything right except that after running solution I got this error in browser:

```
Uncaught TypeError: Router is not a constructor
    at eval (eval at <anonymous> (app.js:1654), <anonymous>:7:19)
    at Object.<anonymous> (app.js:1654)
    at __webpack_require__ (app.js:1299)
    at fn (app.js:720)
    at eval (eval at <anonymous> (app.js:1502), <anonymous>:7:16)
    at Object.<anonymous> (app.js:1502)
    at __webpack_require__ (app.js:1299)
    at fn (app.js:720)
    at Object.<anonymous> (app.js:1807)
    at __webpack_require__ (app.js:1299)
```
It could be that this is connected to [this](https://github.com/vuejs/vue-router/issues/1202) issue but since this is all new to me I`m not sure 
I have uploaded example into [repo](https://github.com/Vertygo/AspNetCore-Vue-TypeScript-WebPack)

**Comment by Vertygo** [comment]
As described in [this issue](https://github.com/vuejs/vue-router/issues/1202) we should add vue-router [alias ](https://github.com/Vertygo/AspNetCore-Vue-TypeScript-WebPack/blob/master/build/webpack.base.conf.js#L32)in webpack.

**Comment by justinyoo** [comment]
@Vertygo Thanks for raising this issue. Yes, it occurs after the breaking change of vue.js 2.2.0. I will update this repo soon.

**Comment by justinyoo** [comment]
@Vertygo Just FYI,

Seems that the router issue has been fixed on `vue@2.2.1`. I'm testing it against `vue@2.2.1`, `typescript@2.2.1` and `vue-router@2.2.0`. We don't need to add an alias for the router any more.

I followed the new recommendation described in the [official guide](https://vuejs.org/v2/guide/typescript.html).

**Comment by Vertygo** [comment]
That is odd because I`m using [vue 2.2.1](https://github.com/Vertygo/AspNetCore-Vue-TypeScript-WebPack/blob/master/package.json#L22) and vue-router [2.3.0](https://github.com/Vertygo/AspNetCore-Vue-TypeScript-WebPack/blob/master/package.json#L24). Maybe its issue with vue-router 2.3.0?

**Comment by justinyoo** [comment]
@Vertygo Not quite sure. I always use [`vue-cli`](https://github.com/vuejs/vue-cli) to install the basic template as a starting point. All sample codes in this repo are using the basic template which uses `vue-router@2.2.0`.
